# Generated by Django 5.0.6 on 2024-06-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_teammodel_delete_feedbackmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammodel',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AddField(
            model_name='teammodel',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
