# Generated by Django 5.0.6 on 2024-06-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_teammodel_options_teammodel_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamModel',
        ),
    ]
