# Generated by Django 5.0.6 on 2024-06-15 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='image2',
        ),
    ]
