# Generated by Django 5.0.6 on 2024-06-15 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_image_productmodel_image1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='image1',
            new_name='image',
        ),
    ]
